// Package asteriskcfg owns the two auto-generated PJSIP config files didapi
// writes alongside the operator-managed pjsip.conf:
//
//   - /etc/asterisk/pjsip_users.conf      — per-user SIP-account endpoints
//                                           (REGISTER targets for end-users)
//   - /etc/asterisk/pjsip_suppliers.conf  — per-supplier identify blocks
//                                           feeding the shared [supplier-trunk]
//
// Lifting these out of internal/web removes the import cycle that previously
// blocked internal/resellerapi from rewriting either file: the reseller API
// can now create/delete SIP peers and the underlying PJSIP reload happens
// through the same code path the admin GUI uses.
//
// Every public function is best-effort: errors get logged and dropped because
// the DB row is the source of truth and any subsequent successful regen
// rewrites the file from scratch.
package asteriskcfg

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"os/user"
	"strconv"
	"strings"
	"time"

	"didstorage/internal/db"
)

// File paths the generated configs land at. Asterisk's pjsip.conf includes
// both via `#include pjsip_users.conf` / `#include pjsip_suppliers.conf`.
const (
	PJSIPUsersPath     = "/etc/asterisk/pjsip_users.conf"
	PJSIPSuppliersPath = "/etc/asterisk/pjsip_suppliers.conf"
)

// reloadTimeout caps how long we wait for `asterisk -rx "pjsip reload"`.
const reloadTimeout = 15 * time.Second

// RegenPJSIPUsers writes pjsip_users.conf from the active sip_accounts rows
// and runs `asterisk -rx "pjsip reload"`. Best-effort: errors are logged.
// Returns nil on full success, or the first non-nil error encountered for
// callers that want to surface them (handlers usually ignore the return).
func RegenPJSIPUsers(pg *db.DB, log *slog.Logger) error {
	ctx, cancel := context.WithTimeout(context.Background(), reloadTimeout)
	defer cancel()

	rows, err := pg.Query(ctx, `
		SELECT s.username, s.realm, s.ha1, s.user_id
		  FROM sip_accounts s
		  JOIN users u ON u.id = s.user_id
		 WHERE u.status = 'active'`)
	if err != nil {
		log.Error("regenPJSIPUsers query", "err", err)
		return err
	}
	defer rows.Close()

	var b strings.Builder
	b.WriteString("; AUTO-GENERATED by didapi — do not edit by hand.\n\n")
	for rows.Next() {
		var user, realm, h1 string
		var uid int64
		if err := rows.Scan(&user, &realm, &h1, &uid); err != nil {
			continue
		}
		fmt.Fprintf(&b, "[%s]\n", user)
		b.WriteString("type=endpoint\n")
		b.WriteString("context=from-account\n")
		b.WriteString("disallow=all\n")
		b.WriteString("allow=ulaw,alaw,opus,g722\n")
		b.WriteString("direct_media=no\n")
		b.WriteString("disable_direct_media_on_nat=yes\n")
		b.WriteString("rtp_symmetric=yes\n")
		b.WriteString("force_rport=yes\n")
		b.WriteString("rewrite_contact=yes\n")
		b.WriteString("dtmf_mode=rfc4733\n")
		b.WriteString("ice_support=no\n")
		b.WriteString("trust_id_inbound=yes\n")
		b.WriteString("send_pai=yes\n")
		fmt.Fprintf(&b, "auth=%s-auth\n", user)
		fmt.Fprintf(&b, "aors=%s\n\n", user)
		fmt.Fprintf(&b, "[%s-auth]\ntype=auth\nauth_type=md5\nrealm=%s\nusername=%s\nmd5_cred=%s\n\n", user, realm, user, h1)
		fmt.Fprintf(&b, "[%s]\ntype=aor\nmax_contacts=2\nremove_existing=yes\nqualify_frequency=30\nqualify_timeout=3.0\n\n", user)
	}

	if err := WriteFileAtomic(PJSIPUsersPath, []byte(b.String())); err != nil {
		log.Error("regenPJSIPUsers write", "err", err, "path", PJSIPUsersPath)
		return err
	}
	if out, err := exec.Command("asterisk", "-rx", "pjsip reload").CombinedOutput(); err != nil {
		log.Warn("pjsip reload failed", "err", err, "out", string(out))
		return err
	}
	log.Info("pjsip users regenerated")
	return nil
}

// RegenSupplierIdentifies writes pjsip_suppliers.conf from
// supplier_ip_groups + supplier_ip_group_members and runs `pjsip reload`.
// One identify block per supplier (keyed by supplier.id so renames don't
// break Asterisk references). Suppliers with zero matches are omitted (a
// match-less identify block is a PJSIP config error).
func RegenSupplierIdentifies(pg *db.DB, log *slog.Logger) error {
	ctx, cancel := context.WithTimeout(context.Background(), reloadTimeout)
	defer cancel()

	rows, err := pg.Query(ctx, `
		SELECT s.id, s.name,
		       COALESCE(host(m.cidr), ''),
		       COALESCE(m.hostname,   '')
		  FROM suppliers s
		  JOIN supplier_ip_groups g ON g.supplier_id = s.id
		  JOIN supplier_ip_group_members m ON m.group_id = g.id
		 ORDER BY s.id, m.cidr NULLS LAST, m.hostname NULLS LAST`)
	if err != nil {
		log.Error("regenSupplierIdentifies query", "err", err)
		return err
	}
	defer rows.Close()

	type supplier struct {
		ID      int64
		Name    string
		Matches []string
		seen    map[string]bool
	}
	bySupplier := map[int64]*supplier{}
	var order []int64
	for rows.Next() {
		var sid int64
		var name, ip, host string
		if err := rows.Scan(&sid, &name, &ip, &host); err != nil {
			continue
		}
		s, ok := bySupplier[sid]
		if !ok {
			s = &supplier{ID: sid, Name: name, seen: map[string]bool{}}
			bySupplier[sid] = s
			order = append(order, sid)
		}
		v := ip
		if v == "" {
			v = host
		}
		if v == "" || s.seen[v] {
			continue
		}
		s.seen[v] = true
		s.Matches = append(s.Matches, v)
	}

	var b strings.Builder
	b.WriteString("; AUTO-GENERATED by didapi — do not edit by hand.\n")
	b.WriteString("; Source: supplier_ip_groups + supplier_ip_group_members.\n")
	b.WriteString("; Every match (IP/CIDR or hostname) across all of a supplier's\n")
	b.WriteString("; groups feeds the shared [supplier-trunk] endpoint defined in\n")
	b.WriteString("; pjsip.conf. Hostnames are resolved by PJSIP at the next\n")
	b.WriteString("; `pjsip reload` (which runs immediately after this file is\n")
	b.WriteString("; written).\n\n")
	for _, sid := range order {
		s := bySupplier[sid]
		if len(s.Matches) == 0 {
			continue
		}
		fmt.Fprintf(&b, "; supplier %d — %s\n", s.ID, s.Name)
		fmt.Fprintf(&b, "[supplier-%d-id]\n", s.ID)
		b.WriteString("type=identify\n")
		b.WriteString("endpoint=supplier-trunk\n")
		for _, m := range s.Matches {
			fmt.Fprintf(&b, "match=%s\n", m)
		}
		b.WriteString("\n")
	}

	if err := WriteFileAtomic(PJSIPSuppliersPath, []byte(b.String())); err != nil {
		log.Error("regenSupplierIdentifies write", "err", err, "path", PJSIPSuppliersPath)
		return err
	}
	if out, err := exec.Command("asterisk", "-rx", "pjsip reload").CombinedOutput(); err != nil {
		log.Warn("pjsip reload after supplier-identifies regen failed", "err", err, "out", string(out))
		return err
	}
	log.Info("supplier identifies regenerated", "suppliers", len(order))
	return nil
}

// WriteFileAtomic writes data to path via path.new + rename, then chgrps to
// the asterisk group so Asterisk (running as user asterisk) can read it.
// didapi runs as user didstorage; without the chgrp the file would land
// didstorage:didstorage 0640 and Asterisk's `#include` would silently fail
// with "Permission denied", which invalidates the whole pjsip.conf parse
// and brings the SIP transport down entirely. We learned this the hard way
// during the 168.119.33.30 bootstrap (May 2026) — see DEPLOY.md.
//
// chgrp failure is non-fatal: a missing asterisk group means Asterisk
// isn't installed yet (cold-boot ordering) and the next regen will catch
// it. We log a warning so the operator can see what's going on.
func WriteFileAtomic(path string, data []byte) error {
	tmp := path + ".new"
	if err := os.WriteFile(tmp, data, 0o640); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		return err
	}
	if g, err := user.LookupGroup("asterisk"); err == nil {
		if gid, err := strconv.Atoi(g.Gid); err == nil {
			// -1 keeps the current owner (didstorage); we only change group.
			_ = os.Chown(path, -1, gid)
			// chmod is defensive — WriteFile already used 0o640 but a
			// process-wide umask could mask group-read off (umask 027 → 0o620).
			_ = os.Chmod(path, 0o640)
		}
	}
	return nil
}
