-- Common countries for the v1 catalog. More can be added by admin later.
INSERT INTO countries (iso, name) VALUES
  ('US','United States'),
  ('GB','United Kingdom'),
  ('CA','Canada'),
  ('AU','Australia'),
  ('DE','Germany'),
  ('FR','France'),
  ('NL','Netherlands'),
  ('ES','Spain'),
  ('IT','Italy'),
  ('IE','Ireland'),
  ('SE','Sweden'),
  ('NO','Norway'),
  ('FI','Finland'),
  ('DK','Denmark'),
  ('PL','Poland'),
  ('CZ','Czechia'),
  ('AT','Austria'),
  ('CH','Switzerland'),
  ('BE','Belgium'),
  ('PT','Portugal'),
  ('JP','Japan'),
  ('SG','Singapore'),
  ('HK','Hong Kong'),
  ('NZ','New Zealand'),
  ('ZA','South Africa'),
  ('BR','Brazil'),
  ('MX','Mexico'),
  ('AR','Argentina'),
  ('IL','Israel'),
  ('AE','United Arab Emirates'),
  ('IN','India'),
  ('PH','Philippines'),
  ('MY','Malaysia'),
  ('TH','Thailand'),
  ('ID','Indonesia')
ON CONFLICT (iso) DO NOTHING;
